-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,"%Y-%m-%d") as PUBLISHED_DATE
FROM BOOK b JOIN AUTHOR a
WHERE b.author_id = a.author_id 
AND CATEGORY = '경제'
ORDER BY PUBLISHED_DATE